# Generated by Django 4.2.28 on 2026-02-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField(unique=True, verbose_name='カードID (Passcode)')),
                ('konami_id', models.IntegerField(blank=True, null=True, verbose_name='コナミID')),
                ('name', models.CharField(max_length=300, verbose_name='カード名')),
                ('name_ja', models.CharField(blank=True, max_length=300, verbose_name='カード名（日本語）')),
                ('card_type', models.CharField(max_length=100, verbose_name='カードタイプ')),
                ('frame_type', models.CharField(blank=True, max_length=50, verbose_name='フレームタイプ')),
                ('description', models.TextField(verbose_name='カード効果・説明')),
                ('atk', models.IntegerField(blank=True, null=True, verbose_name='ATK')),
                ('def_points', models.IntegerField(blank=True, null=True, verbose_name='DEF')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='レベル/ランク')),
                ('race', models.CharField(blank=True, max_length=100, verbose_name='種族')),
                ('attribute', models.CharField(blank=True, max_length=50, verbose_name='属性')),
                ('archetype', models.CharField(blank=True, max_length=200, verbose_name='アーキタイプ')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='カード画像URL')),
                ('image_url_small', models.URLField(blank=True, max_length=500, verbose_name='カード画像URL（小）')),
                ('image_url_cropped', models.URLField(blank=True, max_length=500, verbose_name='カード画像URL（トリミング）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('api_url', models.URLField(blank=True, max_length=500, verbose_name='YGOPRODeck URL')),
            ],
            options={
                'verbose_name': 'カード',
                'verbose_name_plural': 'カード一覧',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=300, verbose_name='セット名')),
                ('set_code', models.CharField(max_length=50, verbose_name='セットコード')),
                ('set_rarity', models.CharField(max_length=100, verbose_name='レアリティ')),
                ('set_rarity_code', models.CharField(blank=True, max_length=20, verbose_name='レアリティコード')),
                ('cardmarket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cardmarket価格 (€)')),
                ('tcgplayer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='TCGPlayer価格 ($)')),
                ('ebay_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='eBay価格 ($)')),
                ('amazon_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amazon価格 ($)')),
                ('coolstuffinc_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CoolStuffInc価格 ($)')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最安値 ($)')),
                ('min_price_source', models.CharField(blank=True, max_length=50, verbose_name='最安値ソース')),
                ('price_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='価格更新日時')),
                ('price_available', models.BooleanField(default=True, verbose_name='価格取得可能')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_sets', to='cards.card', verbose_name='カード')),
            ],
            options={
                'verbose_name': 'カードセット',
                'verbose_name_plural': 'カードセット一覧',
                'ordering': ['min_price'],
                'unique_together': {('card', 'set_code')},
            },
        ),
    ]
