# Generated by Django 4.2.28 on 2026-02-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_index', models.IntegerField(verbose_name='アートワーク番号')),
                ('image_id', models.IntegerField(verbose_name='画像ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='画像URL（全体）')),
                ('image_url_small', models.URLField(blank=True, max_length=500, verbose_name='画像URL（小）')),
                ('image_url_cropped', models.URLField(blank=True, max_length=500, verbose_name='画像URL（クロップ）')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='cards.card', verbose_name='カード')),
            ],
            options={
                'verbose_name': 'カードアートワーク',
                'verbose_name_plural': 'カードアートワーク一覧',
                'ordering': ['artwork_index'],
                'unique_together': {('card', 'artwork_index')},
            },
        ),
    ]
