# Generated by Django 4.2.28 on 2026-02-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_add_card_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description_ja',
            field=models.TextField(blank=True, verbose_name='カード効果・説明（日本語）'),
        ),
        migrations.AddField(
            model_name='card',
            name='linkval',
            field=models.IntegerField(blank=True, null=True, verbose_name='リンク値'),
        ),
        migrations.AddField(
            model_name='card',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='アクセス数'),
        ),
        migrations.AddField(
            model_name='cardset',
            name='set_name_ja',
            field=models.CharField(blank=True, max_length=300, verbose_name='セット名（日本語）'),
        ),
    ]
