# Generated by Django 4.2.28 on 2026-02-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_add_ja_fields_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='linkmarkers',
            field=models.CharField(blank=True, max_length=200, verbose_name='リンクマーカー'),
        ),
        migrations.AddField(
            model_name='card',
            name='scale',
            field=models.IntegerField(blank=True, null=True, verbose_name='ペンデュラムスケール'),
        ),
    ]
