# Generated by Django 4.2.28 on 2026-02-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rakuten_min_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='楽天最安値 (¥)'),
        ),
    ]
