# Generated by Django 4.2.28 on 2026-02-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_card_rakuten_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rakuten_affiliate_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='楽天アフィリエイトURL'),
        ),
    ]
